bug_report_template:
  name: "Bug Report 🐛"
  description: "File a bug report to help improve our project"
  title: "[BUG] "
  labels: 
    - bug
  assignees: []

  about: 
    description: "A concise description of what you're experiencing."

  additional_information: 
    description: "Describe any additional information here, such as error messages, logs, or steps you've already tried to troubleshoot the issue."

  screenshots: 
    description: "Add sufficient screenshots to explain your issue."

  browser: 
    description: "What browser are you seeing the problem on?"
    options:
      - "Chrome"
      - "Firefox"
      - "Safari"
      - "Edge"
      - "Other (please specify): ______________"

  agree_code_of_conduct: 
    description: "By filing this issue, I agree to abide by this project's Code of Conduct."

  first_time_contributor: 
    description: "Include this if you're a first-time contributor and interested in working on this issue."

  record_3_things: 
    description: "Record 3 things at last"
    options:
      - "I Agree to follow this project's Code of Conduct"
      - "I'm a SSOC partz contributor"
      - "I want to work on this issue"
