name: "Bug Report 🐛"
description: "File a bug report to help improve our project"
title: "[BUG] "
labels: bug
assignees: []

body:
  - type: checkboxes
    options:
      - name: "Is there an existing issue for this? 🔍"
        description: "Please search to see if an issue already exists for the bug you encountered."
        required: true
        checked: false
        enabled: true
        hidden: false
      - name: "I have searched the existing issues."

  - type: textarea
    name: "What happened? 🚨"
    description: "A concise description of what you're experiencing."
    required: true
    checked: false
    enabled: true
    hidden: false

  - type: textarea
    name: "Add Screenshots 📸"
    description: "Add sufficient screenshots to explain your issue."
    required: false
    checked: false
    enabled: true
    hidden: false

  - type: checkboxes
    options:
      - name: "What browser are you seeing the problem on? 🌐"
        description: "Select the appropriate browser from the options below."
        required: true
        checked: false
        enabled: true
        hidden: false
      - name: "Chrome"
      - name: "Firefox"
      - name: "Safari"
      - name: "Edge"
      - name: "Other (please specify): ______________"

  - type: checkbox
    name: "I Agree to follow this project's Code of Conduct ✔️"
    description: "By filing this issue, I agree to abide by this project's Code of Conduct."
    required: true
    checked: false
    enabled: true
    hidden: false

  - type: checkboxes
    options:
      - name: "I'm a first-time contributor 🌟"
        description: "I want to work on this issue. Include this if you're a first-time contributor and interested in working on this issue."
        required: false
        checked: false
        enabled: true
        hidden: false
      - name: "I'm a SSOC partz contributor"
      - name: "I want to work on this issue"
