name: Bug report
description: Create a bug report
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please search to see if an issue already exists for the bug you encountered before submitting a new report.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: What happened?
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the issue.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: What browser are you seeing the problem on?
      description: Select the appropriate browser from the options below.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: Other (please specify): _ _ _ _ _ _ _ _ _
  - type: checkboxes
    attributes:
      label: Additional Options
      description: |
        Select any additional options that apply.
      options:
        - label: I Agree to follow this project's Code of Conduct
        - label: I'm a SSOC partz contributor
        - label: I want to work on this issue
